Rework
ExMod-Team/Common-Utils pull request #1
Opened 2024-08-17 22:11 UTC by Mikihero

2024-08-17 22:44 UTC, Mikihero commented
@Misfiy review my pr !!

2024-08-18 11:50 UTC, VALERA771 approved these changes
Okay. Hope that project is compiling and everything is working as expected

2024-08-18 14:44 UTC, Misfiy approved these changes

2024-09-03 15:37 UTC, vladflotsky requested changes

2024-09-03 15:37 UTC, vladflotsky commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
Please do not change names, you will break a lot of configs

2024-09-03 15:37 UTC, vladflotsky commented on Common Utilities/Config.cs
> +                            NewRole = RoleTypeId.Spectator.ToString(),
Please do not change names, you will break a lot of configs

2024-09-03 15:37 UTC, vladflotsky commented on Common Utilities/EventHandlers/ServerHandlers.cs
> +        public ServerHandlers(Plugin plugin) => config = plugin.Config;
Don't do this, you break reloading configs dynamically. Just create the only static instance of the main plugin class and use it

2024-09-03 15:37 UTC, VladTheCow commented on Common Utilities/EventHandlers/ServerHandlers.cs
> +        }
It's not impossible to disable changing rooms' colors?

2024-09-03 15:37 UTC, vladflotsky commented on Common Utilities/Plugin.cs
> +    public override string Author { get; } = "ExMod-Team, overhaul by Mikihero";
Please don't specify yourself here

2024-09-03 15:37 UTC, VladTheCow commented on Common Utilities/Plugin.cs
> +        Log.Info($"Registering EventHandlers..");
Either remove logs or make them debug

2024-09-03 15:49 UTC, Mikihero commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
configs will break and need to be updated anyway because of other changes, I think that makes it a good time to update the naming to something easier to work with

2024-09-03 16:08 UTC, Mikihero commented on Common Utilities/EventHandlers/ServerHandlers.cs
> +        public ServerHandlers(Plugin plugin) => config = plugin.Config;
I've changed it, never used dynamic config reloads so not sure if this is better

2024-09-03 16:13 UTC, VladTheCow requested changes

2024-09-03 16:13 UTC, VladTheCow commented on Common Utilities/Config.cs
> +        public bool ChangeWarheadColor { get; set; } = true;
```suggestion
        public bool ChangeWarheadColor { get; set; } = false;
```

2024-09-03 16:13 UTC, VladTheCow commented on Common Utilities/EventHandlers/ServerHandlers.cs
> +
You forgot about the handler of the OnWarheadStopping event

2024-09-03 16:14 UTC, VladTheCow commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
What other changes break the config?

2024-09-03 16:54 UTC, Mikihero commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
a lot of things in the config are renamed, added or removed, people will need to check it out regardless

2024-09-04 11:00 UTC, Misfiy commented on Common Utilities/EventHandlers/ServerHandlers.cs
> +            if (config.ChangeWarheadColor || Warhead.IsLocked)
r u sure this would give intended behavior?

2024-09-04 11:22 UTC, Mikihero commented on Common Utilities/EventHandlers/ServerHandlers.cs
> +            if (config.ChangeWarheadColor || Warhead.IsLocked)
typical brain fart moment

2024-09-08 09:10 UTC, VladTheCow commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
What exactly? This plugin hasn't been updated since the last major update, I don't see the point of adding breaking changes meanwhile we can avoid them

2024-09-08 09:13 UTC, VladTheCow commented
Did you test all changes at all?

2024-09-08 17:25 UTC, Mikihero commented
everything before your first review was tested, everything after wasn't, if you want I can quickly check if everything is still fine

2024-09-21 11:34 UTC, Mikihero commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
These 2 changes can't really be avoided because the functionality behind them won't work otherwise, everything else is either not breaking or is not required (but would be nice to change) and thus can be removed if we still want to push for a non-breaking config wise update

https://github.com/ExMod-Team/Common-Utils/pull/1/files#diff-23ccbd2ffab239a3846aa258aadfaa57d70b72680a3570adb56b50fd9e486a3eR23-R33

https://github.com/ExMod-Team/Common-Utils/pull/1/files#diff-23ccbd2ffab239a3846aa258aadfaa57d70b72680a3570adb56b50fd9e486a3eR74-R78

2024-09-22 19:35 UTC, VladTheCow commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
I don't get how it's related to changing the current files causing breaking changes

2024-09-22 19:48 UTC, Mikihero commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
these changes add new features that have configs, this will make people update their configs to reflect what they want from those features exactly, imo it's a good time to make changes like these but in the end, it ultimately doesn't matter so if you insist I can just revert these

2024-09-22 19:54 UTC, VladTheCow commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
The thing is a lot of people have the large 914 inventory config, it will be terrible for them to update, so I would like you to revert them

2024-09-22 19:55 UTC, VladTheCow requested changes

2024-09-22 19:55 UTC, VladTheCow commented on Common Utilities/Config.cs
> -        public bool RestrictiveDisarming { get; set; } = true;
Why did you remove it?

2024-09-22 19:57 UTC, VladTheCow commented
Also it will be nice if make all features disabled by default, for example, auto nuke, periodical broadcast message and etc

2024-09-22 20:07 UTC, Mikihero commented on Common Utilities/Config.cs
> +                            NewItem = ItemType.MicroHID.ToString(),
alright

2024-09-22 20:42 UTC, Mikihero commented
> Also it will be nice if make all features disabled by default, for example, auto nuke, periodical broadcast message and etc

sounds good, I will get on it when I can

2024-09-22 20:43 UTC, Mikihero commented on Common Utilities/Config.cs
> -        public bool RestrictiveDisarming { get; set; } = true;
first one was replaced, second one is a base game feature so I don't see a reason to keep it

2024-09-23 15:29 UTC, Mikihero commented
actually, I'll leave some features enabled like the disarmed escapes since disabling it would require me to delete that part from the config and it serves as a guide for people on how to input the values correctly

2024-09-28 18:40 UTC, VladTheCow approved these changes

2024-09-28 18:40 UTC, merged